In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls /content/drive/MyDrive/

'Colab Notebooks'   ml-alrIEEEna-gehu

In [ ]:
file_path = '/content/drive/MyDrive/ml-alrIEEEna-gehu'

In [ ]:
import pandas as pd

### did some feature engineering with train and test dataset and also did data cleaning

In [ ]:
trainDf = pd.read_csv(f'{file_path}/TRAIN.csv')
testDf = pd.read_csv(f'{file_path}/TEST.csv')

In [ ]:
trainDf.head()

,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,...,F39,F40,F41,F42,F43,F44,F45,F46,F47,Class
0,0.185570,0.004568,0.005362,0.003335,0.005415,0.004895,0.012764,0.120138,0.140450,3.361753,...,0.041526,-0.230857,0.003310,0.042250,0.005975,0.002104,0.013878,0.001518,0.011347,0
1,0.369536,0.003983,0.003386,0.004902,0.007570,0.012136,0.118050,0.323925,0.132093,2.766117,...,-0.141285,-6.222857,0.834177,0.227968,0.018463,-0.020487,0.001246,0.007489,0.008724,1
2,0.602510,0.008442,0.012961,0.012870,0.046885,0.115401,0.065688,0.306677,0.498805,4.521201,...,0.011334,10.335251,-0.276614,-0.198900,-0.012756,0.014286,-0.001866,0.002687,0.013452,1
3,0.347957,0.064721,0.013611,0.011541,0.006492,0.008690,0.013192,0.164553,0.298665,3.170847,...,0.190479,2.864912,-1.921939,0.891690,1.108098,0.635431,0.081368,-0.000225,0.009166,0
4,0.233653,0.012217,0.010088,0.022095,0.026040,0.015062,0.016063,0.084648,0.213367,8.150943,...,0.203164,0.001812,-0.092731,0.005280,-0.213985,0.032195,0.002081,0.028930,-0.025912,1

In [ ]:
testDf.head()

,ID,F01,F02,F03,F04,F05,F06,F07,F08,F09,...,F38,F39,F40,F41,F42,F43,F44,F45,F46,F47
0,1,0.277497,0.011515,0.009359,0.011706,0.015613,0.063679,0.021114,0.152000,0.220904,...,2.974426,0.009399,0.015668,0.001999,-0.000937,0.010605,-0.001117,0.043216,-0.000077,-0.040124
1,2,0.158754,0.013861,0.020935,0.002451,0.005939,0.006830,0.006934,0.117209,0.103432,...,2.619811,0.029324,-0.003211,0.037691,-0.083697,0.006595,0.044507,0.007523,-0.000283,-0.007837
2,3,0.504418,0.009106,0.007395,0.009073,0.029486,0.086782,0.122499,0.179376,0.445695,...,4.411972,-0.171520,-0.866895,-0.070657,0.034070,-0.000493,-0.011417,-0.004844,-0.034235,-0.001832
3,4,0.556345,0.005370,0.005670,0.005167,0.013731,0.014570,0.014776,0.522296,0.189882,...,2.709162,0.044236,19.880789,-2.144453,-1.792552,-0.034137,-0.051971,-0.085069,-0.000110,0.045889
4,5,0.128356,0.010014,0.016144,0.003891,0.004472,0.005297,0.007538,0.075874,0.101176,...,2.872020,-0.056908,0.006535,0.070059,-0.007989,0.004089,-0.000206,-0.011331,0.000441,-0.025263

In [ ]:
trainDf.isna().sum().sum()

np.int64(0)

In [ ]:
testDf.isnull().sum().sum()

np.int64(0)

In [ ]:
trainDf.shape

(43776, 48)

In [ ]:
trainDf.describe()

,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,...,F39,F40,F41,F42,F43,F44,F45,F46,F47,Class
count,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,...,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000,43776.000000
mean,0.567525,0.014285,0.015551,0.026779,0.087637,0.155142,0.150656,0.255644,0.361146,3.762811,...,0.023477,-0.039795,0.005846,-0.000089,0.003215,0.001007,0.004599,0.003981,-0.006780,0.395445
std,0.738884,0.019607,0.022504,0.050725,0.188394,0.377655,0.339948,0.354816,0.440134,1.271343,...,0.707224,8.462749,1.631328,1.103486,0.354742,0.171935,0.201611,0.202130,0.562031,0.488952
min,0.100025,0.003001,0.000752,0.000682,0.000835,0.000854,0.000702,0.001399,0.001164,0.038349,...,-22.647806,-28.026880,-9.109769,-9.275399,-10.607320,-5.910117,-11.029342,-18.853842,-44.878769,0.000000
25%,0.198843,0.004778,0.005437,0.006290,0.012050,0.014112,0.015084,0.072098,0.128780,3.192588,...,-0.036589,-0.254039,-0.117789,-0.015759,-0.011839,-0.007214,-0.005226,-0.000826,-0.008882,0.000000
50%,0.288778,0.007988,0.008905,0.012619,0.023681,0.032396,0.029157,0.119095,0.214665,3.604579,...,-0.000210,-0.000757,-0.002891,-0.000111,-0.000045,-0.000170,0.000295,0.000092,-0.000083,0.000000
75%,0.528760,0.014382,0.016610,0.027599,0.063469,0.115950,0.116992,0.265227,0.381230,4.035824,...,0.043276,0.171122,0.107351,0.013399,0.009806,0.005892,0.006058,0.002405,0.007418,1.000000
max,12.779628,0.199925,0.506419,0.851009,5.017180,7.249545,6.556998,5.960009,5.085546,50.624777,...,89.378571,28.471415,10.907778,9.374269,11.399358,9.139964,18.623611,8.960172,40.818882,1.000000

In [ ]:
trainDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43776 entries, 0 to 43775
Data columns (total 48 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   F01     43776 non-null  float64
 1   F02     43776 non-null  float64
 2   F03     43776 non-null  float64
 3   F04     43776 non-null  float64
 4   F05     43776 non-null  float64
 5   F06     43776 non-null  float64
 6   F07     43776 non-null  float64
 7   F08     43776 non-null  float64
 8   F09     43776 non-null  float64
 9   F10     43776 non-null  float64
 10  F11     43776 non-null  float64
 11  F12     43776 non-null  float64
 12  F13     43776 non-null  float64
 13  F14     43776 non-null  float64
 14  F15     43776 non-null  float64
 15  F16     43776 non-null  float64
 16  F17     43776 non-null  float64
 17  F18     43776 non-null  float64
 18  F19     43776 non-null  float64
 19  F20     43776 non-null  float64
 20  F21     43776 non-null  float64
 21  F22     43776 non-null  float64
 22  F23     43776 non-null  float64
 23  F24     43776 non-null  float64
 24  F25     43776 non-null  float64
 25  F26     43776 non-null  float64
 26  F27     43776 non-null  float64
 27  F28     43776 non-null  float64
 28  F29     43776 non-null  float64
 29  F30     43776 non-null  float64
 30  F31     43776 non-null  float64
 31  F32     43776 non-null  float64
 32  F33     43776 non-null  float64
 33  F34     43776 non-null  float64
 34  F35     43776 non-null  float64
 35  F36     43776 non-null  float64
 36  F37     43776 non-null  float64
 37  F38     43776 non-null  float64
 38  F39     43776 non-null  float64
 39  F40     43776 non-null  float64
 40  F41     43776 non-null  float64
 41  F42     43776 non-null  float64
 42  F43     43776 non-null  float64
 43  F44     43776 non-null  float64
 44  F45     43776 non-null  float64
 45  F46     43776 non-null  float64
 46  F47     43776 non-null  float64
 47  Class   43776 non-null  int64
dtypes: float64(47), int64(1)
memory usage: 16.0 MB

In [ ]:
trainDf["Class"].value_counts()

Class
0    26465
1    17311
Name: count, dtype: int64

In [ ]:
trainDf.duplicated().sum()

np.int64(738)

In [ ]:
trainDf = trainDf.drop_duplicates()

In [ ]:
trainDf.duplicated().sum()

np.int64(0)

## Logistic Regression - trying to train on this algo

### import required libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
    confusion_matrix,
    classification_report,
    matthews_corrcoef,
    log_loss,
    average_precision_score,
    precision_recall_curve
)

In [ ]:
trainDf.head()

,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,...,F39,F40,F41,F42,F43,F44,F45,F46,F47,Class
0,0.185570,0.004568,0.005362,0.003335,0.005415,0.004895,0.012764,0.120138,0.140450,3.361753,...,0.041526,-0.230857,0.003310,0.042250,0.005975,0.002104,0.013878,0.001518,0.011347,0
1,0.369536,0.003983,0.003386,0.004902,0.007570,0.012136,0.118050,0.323925,0.132093,2.766117,...,-0.141285,-6.222857,0.834177,0.227968,0.018463,-0.020487,0.001246,0.007489,0.008724,1
2,0.602510,0.008442,0.012961,0.012870,0.046885,0.115401,0.065688,0.306677,0.498805,4.521201,...,0.011334,10.335251,-0.276614,-0.198900,-0.012756,0.014286,-0.001866,0.002687,0.013452,1
3,0.347957,0.064721,0.013611,0.011541,0.006492,0.008690,0.013192,0.164553,0.298665,3.170847,...,0.190479,2.864912,-1.921939,0.891690,1.108098,0.635431,0.081368,-0.000225,0.009166,0
4,0.233653,0.012217,0.010088,0.022095,0.026040,0.015062,0.016063,0.084648,0.213367,8.150943,...,0.203164,0.001812,-0.092731,0.005280,-0.213985,0.032195,0.002081,0.028930,-0.025912,1

In [ ]:
testDf.duplicated().sum()

np.int64(0)

In [ ]:
trainDf.duplicated().sum()

np.int64(0)

In [ ]:
X = trainDf.drop('Class', axis=1)
y = trainDf['Class']

In [ ]:
X.head()

,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,...,F38,F39,F40,F41,F42,F43,F44,F45,F46,F47
0,0.185570,0.004568,0.005362,0.003335,0.005415,0.004895,0.012764,0.120138,0.140450,3.361753,...,2.826142,0.041526,-0.230857,0.003310,0.042250,0.005975,0.002104,0.013878,0.001518,0.011347
1,0.369536,0.003983,0.003386,0.004902,0.007570,0.012136,0.118050,0.323925,0.132093,2.766117,...,2.955462,-0.141285,-6.222857,0.834177,0.227968,0.018463,-0.020487,0.001246,0.007489,0.008724
2,0.602510,0.008442,0.012961,0.012870,0.046885,0.115401,0.065688,0.306677,0.498805,4.521201,...,3.423784,0.011334,10.335251,-0.276614,-0.198900,-0.012756,0.014286,-0.001866,0.002687,0.013452
3,0.347957,0.064721,0.013611,0.011541,0.006492,0.008690,0.013192,0.164553,0.298665,3.170847,...,2.473058,0.190479,2.864912,-1.921939,0.891690,1.108098,0.635431,0.081368,-0.000225,0.009166
4,0.233653,0.012217,0.010088,0.022095,0.026040,0.015062,0.016063,0.084648,0.213367,8.150943,...,7.595287,0.203164,0.001812,-0.092731,0.005280,-0.213985,0.032195,0.002081,0.028930,-0.025912

In [ ]:
y.head()

0    0
1    1
2    1
3    0
4    1
Name: Class, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

print("Train size : ",X_train.shape)
print("Test size : ",X_test.shape)

Train size :  (34430, 47)
Test size :  (8608, 47)

### scaling the data

In [ ]:
scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

In [ ]:
model = LogisticRegression(
    solver='saga',
    max_iter=1000,
    C=1.0,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

model_for_scaled = LogisticRegression(
    solver='saga',
    max_iter=1000,
    C=1.0,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

model.fit(X_train,y_train) # without scaled

model_for_scaled.fit(X_train_scaled,y_train) # with scaled

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

LogisticRegression(class_weight='balanced', max_iter=1000, n_jobs=-1,
                   random_state=42, solver='saga')

In [ ]:
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:,1]

y_pred_for_scaled = model_for_scaled.predict(X_test_scaled)
y_pred_for_scaled_proba = model_for_scaled.predict_proba(X_test_scaled)[:,1]

# print the confusion matrix and other metrices also

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall    = recall_score(y_test, y_pred, average='binary')
f1        = f1_score(y_test, y_pred, average='binary')
roc_auc   = roc_auc_score(y_test, y_pred_proba)
mcc       = matthews_corrcoef(y_test, y_pred)
logloss   = log_loss(y_test, y_pred_proba)
avg_prec  = average_precision_score(y_test, y_pred_proba)

metrics = {
    "Accuracy"                    : accuracy,
    "Precision"                   : precision,
    "Recall (Sensitivity)"        : recall,
    "F1 Score"                    : f1,
    "ROC-AUC Score"               : roc_auc,
    "Average Precision (PR-AUC)"  : avg_prec,
    "Matthews Corr. Coeff (MCC)"  : mcc,
    "Log Loss"                    : logloss,
}

cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()
print(f"\n  Confusion Matrix -> TP:{tp}  FP:{fp}  TN:{tn}  FN:{fn}")

accuracy_scaled = accuracy_score(y_test, y_pred_for_scaled)
precision_scaled = precision_score(y_test, y_pred_for_scaled)
recall_scaled    = recall_score(y_test, y_pred_for_scaled, average='binary')
f1_scaled        = f1_score(y_test, y_pred_for_scaled, average='binary')
roc_auc_scaled   = roc_auc_score(y_test, y_pred_for_scaled_proba)
mcc_scaled       = matthews_corrcoef(y_test, y_pred_for_scaled)
logloss_scaled   = log_loss(y_test, y_pred_for_scaled_proba)
avg_prec_scaled  = average_precision_score(y_test, y_pred_for_scaled_proba)

metrics_scaled = {
    "Accuracy scaled"                    : accuracy_scaled,
    "Precision scaled"                   : precision_scaled,
    "Recall (Sensitivity) scaled"        : recall_scaled,
    "F1 Score scaled"                    : f1_scaled,
    "ROC-AUC Score scaled"               : roc_auc_scaled,
    "Average Precision (PR-AUC) scaled"  : avg_prec_scaled,
    "Matthews Corr. Coeff (MCC) scaled"  : mcc_scaled,
    "Log Loss scaled"                    : logloss_scaled,
}

cm_scaled = confusion_matrix(y_test, y_pred_for_scaled)
tn_scaled, fp_scaled, fn_scaled, tp_scaled = cm_scaled.ravel()
print(f"\n  Confusion Matrix scaled -> TP:{tp_scaled}  FP:{fp_scaled}  TN:{tn_scaled}  FN:{fn_scaled}")

for metric, value in metrics.items():
    print(f"  {metric:<35}: {value:.4f}")

print("\n")

for metric, value in metrics_scaled.items():
    print(f"  {metric:<35}: {value:.4f}")

  Confusion Matrix -> TP:1725  FP:905  TN:4241  FN:1737

  Confusion Matrix scaled -> TP:2013  FP:845  TN:4301  FN:1449
  Accuracy                           : 0.6931
  Precision                          : 0.6559
  Recall (Sensitivity)               : 0.4983
  F1 Score                           : 0.5663
  ROC-AUC Score                      : 0.6927
  Average Precision (PR-AUC)         : 0.6956
  Matthews Corr. Coeff (MCC)         : 0.3432
  Log Loss                           : 0.6172


  Accuracy scaled                    : 0.7335
  Precision scaled                   : 0.7043
  Recall (Sensitivity) scaled        : 0.5815
  F1 Score scaled                    : 0.6370
  ROC-AUC Score scaled               : 0.7823
  Average Precision (PR-AUC) scaled  : 0.7699
  Matthews Corr. Coeff (MCC) scaled  : 0.4344
  Log Loss scaled                    : 0.5312

### it didnt perform well as we can see the classification report for both scaled data and given data

In [ ]:
print(classification_report(y_test, y_pred, target_names=["Class 0", "Class 1"]))
print("\n\nScaled")
print(classification_report(y_test, y_pred_for_scaled, target_names=["Class 0", "Class 1"]))

              precision    recall  f1-score   support

     Class 0       0.71      0.82      0.76      5146
     Class 1       0.66      0.50      0.57      3462

    accuracy                           0.69      8608
   macro avg       0.68      0.66      0.66      8608
weighted avg       0.69      0.69      0.68      8608



Scaled
              precision    recall  f1-score   support

     Class 0       0.75      0.84      0.79      5146
     Class 1       0.70      0.58      0.64      3462

    accuracy                           0.73      8608
   macro avg       0.73      0.71      0.71      8608
weighted avg       0.73      0.73      0.73      8608

## Decision tree - tree algo's considered as best for this type of data which contains many features

### import required things

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split,cross_val_score, GridSearchCV
from sklearn.tree import DecisionTreeClassifier,plot_tree, export_text
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, roc_curve, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score, precision_recall_curve
)

In [ ]:
X = trainDf.drop('Class', axis=1)
y = trainDf['Class']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

print("Train size : ",X_train.shape[0])
print("Test size : ",X_test.shape[0])

Train size :  34430
Test size :  8608

### function to print all type of metrices

In [ ]:
def print_metrics(y_true, y_pred, y_proba, label="Model"):
    accuracy  = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='binary')
    recall    = recall_score(y_true, y_pred, average='binary')
    f1        = f1_score(y_true, y_pred, average='binary')
    roc_auc   = roc_auc_score(y_true, y_proba)
    avg_prec  = average_precision_score(y_true, y_proba)
    mcc       = matthews_corrcoef(y_true, y_pred)
    logloss   = log_loss(y_true, y_proba)

    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    specificity = tn / (tn + fp)

    print(f"\n{'='*60}")
    print(f"       {label} - METRICS REPORT")
    print(f"{'='*60}")
    metrics = {
        "Accuracy"                   : accuracy,
        "Precision"                  : precision,
        "Recall (Sensitivity)"       : recall,
        "Specificity (TNR)"          : specificity,
        "F1 Score"                   : f1,
        "ROC-AUC Score"              : roc_auc,
        "Average Precision (PR-AUC)" : avg_prec,
        "Matthews Corr. Coeff (MCC)" : mcc,
        "Log Loss"                   : logloss,
    }
    for k, v in metrics.items():
        print(f"  {k:<35}: {v:.4f}")

    print(f"\n  Confusion Matrix -> TP:{tp}  FP:{fp}  TN:{tn}  FN:{fn}")
    print(f"\n--- Detailed Classification Report ---")
    print(classification_report(y_true, y_pred, target_names=["Class 0", "Class 1"]))
    return metrics, cm

### create model object and train the model

In [ ]:
dt_model = DecisionTreeClassifier(
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight='balanced',
    random_state=42
)

dt_model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

### didnt work well as we can see the metrics report

In [ ]:
y_pred = dt_model.predict(X_test)
y_pred_proba = dt_model.predict_proba(X_test)[:,1]

dt_metrics_default, dt_cm_default = print_metrics(y_test, y_pred, y_pred_proba, "Decision Tree (Default)")

============================================================
       Decision Tree (Default) - METRICS REPORT
============================================================
  Accuracy                           : 0.9420
  Precision                          : 0.9310
  Recall (Sensitivity)               : 0.9243
  Specificity (TNR)                  : 0.9539
  F1 Score                           : 0.9277
  ROC-AUC Score                      : 0.9391
  Average Precision (PR-AUC)         : 0.8910
  Matthews Corr. Coeff (MCC)         : 0.8793
  Log Loss                           : 2.0894

  Confusion Matrix -> TP:3200  FP:237  TN:4909  FN:262

--- Detailed Classification Report ---
              precision    recall  f1-score   support

     Class 0       0.95      0.95      0.95      5146
     Class 1       0.93      0.92      0.93      3462

    accuracy                           0.94      8608
   macro avg       0.94      0.94      0.94      8608
weighted avg       0.94      0.94      0.94      8608

### Gird search (hyperparameter tuning) - finding the best parameters for our algorithms instead of default parameters

In [ ]:
param_grid = {
    'max_depth': [5,10,15,20,None],
    'min_samples_leaf' : [1,5,10,20],
    'criterion' : ['gini','entropy']
}

grid_search = GridSearchCV(
    DecisionTreeClassifier(
        class_weight='balanced',
        random_state=42
    ),
    param_grid,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train,y_train)

print(f"\nBest Parameters: {grid_search.best_params_}")
print(f"Best CV F1 Score: {grid_search.best_score_:.4f}")

Fitting 5 folds for each of 40 candidates, totalling 200 fits

Best Parameters: {'criterion': 'entropy', 'max_depth': None, 'min_samples_leaf': 1}
Best CV F1 Score: 0.9260

### it perform slightly better that default decision tree but still unsatisfied performance

In [ ]:
best_dt = grid_search.best_estimator_
y_pred_tuned = best_dt.predict(X_test)
y_pred_proba_tuned = best_dt.predict_proba(X_test)[:,1]
dt_tuned_metrics,dt_tuned_cm = print_metrics(y_test,y_pred_tuned,y_pred_proba_tuned,"Decision Tree (Tuned)")

============================================================
       Decision Tree (Tuned) - METRICS REPORT
============================================================
  Accuracy                           : 0.9487
  Precision                          : 0.9423
  Recall (Sensitivity)               : 0.9292
  Specificity (TNR)                  : 0.9617
  F1 Score                           : 0.9357
  ROC-AUC Score                      : 0.9455
  Average Precision (PR-AUC)         : 0.9041
  Matthews Corr. Coeff (MCC)         : 0.8930
  Log Loss                           : 1.8508

  Confusion Matrix -> TP:3217  FP:197  TN:4949  FN:245

--- Detailed Classification Report ---
              precision    recall  f1-score   support

     Class 0       0.95      0.96      0.96      5146
     Class 1       0.94      0.93      0.94      3462

    accuracy                           0.95      8608
   macro avg       0.95      0.95      0.95      8608
weighted avg       0.95      0.95      0.95      8608

In [ ]:
feature_names = X.columns.tolist()

importances = best_dt.feature_importances_
feat_df = pd.DataFrame({
    'Feature'   : feature_names,
    'Importance': importances
}).sort_values('Importance', ascending=False)

print("\n--- Top 10 Most Important Features ---")
print(feat_df.head(10).to_string(index=False))

--- Top 10 Most Important Features ---
Feature  Importance
    F19    0.174618
    F29    0.053505
    F08    0.050091
    F09    0.041529
    F01    0.041250
    F39    0.040052
    F25    0.040045
    F38    0.036589
    F27    0.033177
    F30    0.032290

## Random forest - also a tree based algorithm (best for this type of data)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls /content/drive/MyDrive/

'Colab Notebooks'   ml-alrIEEEna-gehu

In [ ]:
file_path = '/content/drive/MyDrive/ml-alrIEEEna-gehu'
trainDf = pd.read_csv(f'{file_path}/TRAIN.csv')
testDf = pd.read_csv(f'{file_path}/TEST.csv')

In [ ]:
trainDf.duplicated().sum()

np.int64(738)

In [ ]:
trainDf.drop_duplicates(inplace=True)

In [ ]:
trainDf.duplicated().sum()

np.int64(0)

In [ ]:
testDf.duplicated().sum()

np.int64(0)

### import required things

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score
)

In [ ]:
X = trainDf.drop('Class',axis=1)
y = trainDf['Class']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

print(f"\nTrain size: {X_train.shape[0]} | Test size: {X_test.shape[0]}")

Train size: 34430 | Test size: 8608

### function to print all mertices

In [ ]:
def print_metrics(y_true, y_pred, y_proba, label="Model"):
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()

    metrics = {
        "Accuracy"                   : accuracy_score(y_true, y_pred),
        "Precision"                  : precision_score(y_true, y_pred),
        "Recall (Sensitivity)"       : recall_score(y_true, y_pred),
        "Specificity (TNR)"          : tn / (tn + fp),
        "F1 Score"                   : f1_score(y_true, y_pred),
        "ROC-AUC Score"              : roc_auc_score(y_true, y_proba),
        "Average Precision (PR-AUC)" : average_precision_score(y_true, y_proba),
        "Matthews Corr. Coeff (MCC)" : matthews_corrcoef(y_true, y_pred),
        "Log Loss"                   : log_loss(y_true, y_proba),
    }

    print(f"\n{'='*60}")
    print(f"       {label} - METRICS REPORT")
    print(f"{'='*60}")
    for k, v in metrics.items():
        print(f"  {k:<35}: {v:.4f}")
    print(f"\n  Confusion Matrix -> TP:{tp}  FP:{fp}  TN:{tn}  FN:{fn}")
    print(f"\n--- Detailed Classification Report ---")
    print(classification_report(y_true, y_pred, target_names=["Class 0", "Class 1"]))
    return metrics

### training **random forest** on default parameters False negative :136 (as in current problem we required to minimise the false negative )

### best till now compared to all above algos

In [ ]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)
y_pred_proba = rf_model.predict_proba(X_test)[:,1]

rf_metrics_default = print_metrics(y_test, y_pred, y_pred_proba, "Random Forest (Default)")

============================================================
       Random Forest (Default) - METRICS REPORT
============================================================
  Accuracy                           : 0.9825
  Precision                          : 0.9955
  Recall (Sensitivity)               : 0.9607
  Specificity (TNR)                  : 0.9971
  F1 Score                           : 0.9778
  ROC-AUC Score                      : 0.9991
  Average Precision (PR-AUC)         : 0.9987
  Matthews Corr. Coeff (MCC)         : 0.9637
  Log Loss                           : 0.0982

  Confusion Matrix -> TP:3326  FP:15  TN:5131  FN:136

--- Detailed Classification Report ---
              precision    recall  f1-score   support

     Class 0       0.97      1.00      0.99      5146
     Class 1       1.00      0.96      0.98      3462

    accuracy                           0.98      8608
   macro avg       0.98      0.98      0.98      8608
weighted avg       0.98      0.98      0.98      8608

### hyperparameter tuning(grid search) apply grid search here for finding best parameters to train the random forest
false negative 147 - not much improvement

In [ ]:
import cudf
from cuml.ensemble import RandomForestClassifier as cuRF
from sklearn.model_selection import train_test_split

X_train_gpu = cudf.DataFrame(X_train)
y_train_gpu = cudf.Series(y_train)
X_test_gpu  = cudf.DataFrame(X_test)


configs = [
    {'n_estimators': 100, 'max_depth': 10, 'max_features': 'sqrt'},
    {'n_estimators': 200, 'max_depth': 20, 'max_features': 'sqrt'},
    {'n_estimators': 300, 'max_depth': 25, 'max_features': 'sqrt'},
    {'n_estimators': 200, 'max_depth': 10, 'max_features': 'log2'},
    {'n_estimators': 200, 'max_depth': 20, 'max_features': 'log2'},
    {'n_estimators': 300, 'max_depth': 25, 'max_features': 'log2'},
    {'n_estimators': 300, 'max_depth': 32, 'max_features': 'sqrt'}
]

best_f1, best_model, best_cfg = 0, None, None

for cfg in configs:
    rf = cuRF(
        n_estimators = cfg['n_estimators'],
        max_depth    = cfg['max_depth'],
        max_features = cfg['max_features'],
        n_bins       = 256,
        random_state = 42
    )

    rf.fit(X_train_gpu, y_train_gpu)

    preds = rf.predict(X_test_gpu).to_numpy()
    f1    = f1_score(y_test, preds)
    print(f"  {cfg}  =>  F1: {f1:.4f}")

    if f1 > best_f1:
        best_f1, best_model, best_cfg = f1, rf, cfg

print(f"\nBest config : {best_cfg}")
print(f"Best F1     : {best_f1:.4f}")

y_pred_tuned       = best_model.predict(X_test_gpu).to_numpy()
y_pred_proba_tuned = best_model.predict_proba(X_test_gpu).to_numpy()[:, 1]
print_metrics(y_test, y_pred_tuned, y_pred_proba_tuned, "Random Forest Tuned (GPU)")

  {'n_estimators': 100, 'max_depth': 10, 'max_features': 'sqrt'}  =>  F1: 0.8533
  {'n_estimators': 200, 'max_depth': 20, 'max_features': 'sqrt'}  =>  F1: 0.9678
  {'n_estimators': 300, 'max_depth': 25, 'max_features': 'sqrt'}  =>  F1: 0.9747
  {'n_estimators': 200, 'max_depth': 10, 'max_features': 'log2'}  =>  F1: 0.8496
  {'n_estimators': 200, 'max_depth': 20, 'max_features': 'log2'}  =>  F1: 0.9681
  {'n_estimators': 300, 'max_depth': 25, 'max_features': 'log2'}  =>  F1: 0.9740
  {'n_estimators': 300, 'max_depth': 32, 'max_features': 'sqrt'}  =>  F1: 0.9756

Best config : {'n_estimators': 300, 'max_depth': 32, 'max_features': 'sqrt'}
Best F1     : 0.9756

============================================================
       Random Forest Tuned (GPU) - METRICS REPORT
============================================================
  Accuracy                           : 0.9807
  Precision                          : 0.9943
  Recall (Sensitivity)               : 0.9575
  Specificity (TNR)                  : 0.9963
  F1 Score                           : 0.9756
  ROC-AUC Score                      : 0.9991
  Average Precision (PR-AUC)         : 0.9988
  Matthews Corr. Coeff (MCC)         : 0.9601
  Log Loss                           : 0.1050

  Confusion Matrix -> TP:3315  FP:19  TN:5127  FN:147

--- Detailed Classification Report ---
              precision    recall  f1-score   support

     Class 0       0.97      1.00      0.98      5146
     Class 1       0.99      0.96      0.98      3462

    accuracy                           0.98      8608
   macro avg       0.98      0.98      0.98      8608
weighted avg       0.98      0.98      0.98      8608

{'Accuracy': 0.9807156133828996,
 'Precision': 0.9943011397720456,
 'Recall (Sensitivity)': 0.9575389948006933,
 'Specificity (TNR)': np.float64(0.9963078118927322),
 'F1 Score': 0.9755738669805768,
 'ROC-AUC Score': np.float64(0.9991468922595959),
 'Average Precision (PR-AUC)': np.float64(0.9987802621654076),
 'Matthews Corr. Coeff (MCC)': np.float64(0.9601170726897137),
 'Log Loss': 0.10500091291171486}

## extra tree - one more tree based algorithm

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls /content/drive/MyDrive/

'Colab Notebooks'   ml-alrIEEEna-gehu

In [ ]:
file_path = '/content/drive/MyDrive/ml-alrIEEEna-gehu'

In [ ]:
!ls /content/drive/MyDrive/ml-alrIEEEna-gehu

TEST.csv  TRAIN.csv

### import required things

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score
)

In [ ]:
trainDf = pd.read_csv(f'{file_path}/TRAIN.csv')

In [ ]:
trainDf.drop_duplicates(inplace=True)
trainDf.duplicated().sum()

np.int64(0)

In [ ]:
X = trainDf.drop('Class',axis=1)
y = trainDf['Class']

In [ ]:
X.head()

,F01,F02,F03,F04,F05,F06,F07,F08,F09,F10,...,F38,F39,F40,F41,F42,F43,F44,F45,F46,F47
0,0.185570,0.004568,0.005362,0.003335,0.005415,0.004895,0.012764,0.120138,0.140450,3.361753,...,2.826142,0.041526,-0.230857,0.003310,0.042250,0.005975,0.002104,0.013878,0.001518,0.011347
1,0.369536,0.003983,0.003386,0.004902,0.007570,0.012136,0.118050,0.323925,0.132093,2.766117,...,2.955462,-0.141285,-6.222857,0.834177,0.227968,0.018463,-0.020487,0.001246,0.007489,0.008724
2,0.602510,0.008442,0.012961,0.012870,0.046885,0.115401,0.065688,0.306677,0.498805,4.521201,...,3.423784,0.011334,10.335251,-0.276614,-0.198900,-0.012756,0.014286,-0.001866,0.002687,0.013452
3,0.347957,0.064721,0.013611,0.011541,0.006492,0.008690,0.013192,0.164553,0.298665,3.170847,...,2.473058,0.190479,2.864912,-1.921939,0.891690,1.108098,0.635431,0.081368,-0.000225,0.009166
4,0.233653,0.012217,0.010088,0.022095,0.026040,0.015062,0.016063,0.084648,0.213367,8.150943,...,7.595287,0.203164,0.001812,-0.092731,0.005280,-0.213985,0.032195,0.002081,0.028930,-0.025912

In [ ]:
y.head()

0    0
1    1
2    1
3    0
4    1
Name: Class, dtype: int64

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")

Train: 34430 | Test: 8608

### to print all metrices

In [ ]:
def print_metrics(y_true, y_pred, y_proba):
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    print(f"\n{'='*60}\n       Extra Trees - METRICS REPORT\n{'='*60}")
    for k, v in {
        "Accuracy"                   : accuracy_score(y_true, y_pred),
        "Precision"                  : precision_score(y_true, y_pred),
        "Recall (Sensitivity)"       : recall_score(y_true, y_pred),
        "Specificity (TNR)"          : tn / (tn + fp),
        "F1 Score"                   : f1_score(y_true, y_pred),
        "ROC-AUC"                    : roc_auc_score(y_true, y_proba),
        "Average Precision (PR-AUC)" : average_precision_score(y_true, y_proba),
        "MCC"                        : matthews_corrcoef(y_true, y_pred),
        "Log Loss"                   : log_loss(y_true, y_proba),
    }.items():
        print(f"  {k:<35}: {v:.4f}")
    print(f"\n  TP:{tp}  FP:{fp}  TN:{tn}  FN:{fn}")
    print(classification_report(y_true, y_pred, target_names=["Class 0", "Class 1"]))

## train the model

In [ ]:
model = ExtraTreesClassifier(
    n_estimators=200,
    max_features='sqrt',
    class_weight='balanced',
    bootstrap=False,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train,y_train)

ExtraTreesClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                     random_state=42)

## **best till now false-negative : 106**

In [ ]:
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)[:,1]

print_metrics(y_test,y_pred,y_pred_proba)

============================================================
       Extra Trees - METRICS REPORT
============================================================
  Accuracy                           : 0.9862
  Precision                          : 0.9961
  Recall (Sensitivity)               : 0.9694
  Specificity (TNR)                  : 0.9975
  F1 Score                           : 0.9826
  ROC-AUC                            : 0.9995
  Average Precision (PR-AUC)         : 0.9993
  MCC                                : 0.9714
  Log Loss                           : 0.0865

  TP:3356  FP:13  TN:5133  FN:106
              precision    recall  f1-score   support

     Class 0       0.98      1.00      0.99      5146
     Class 1       1.00      0.97      0.98      3462

    accuracy                           0.99      8608
   macro avg       0.99      0.98      0.99      8608
weighted avg       0.99      0.99      0.99      8608

## Xgboost (one more tree based algorithm) False negative:84
giving results better that above algos

In [ ]:
import xgboost as xgb
from sklearn.model_selection import  train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score
)

In [ ]:
trainDf = pd.read_csv(f'{file_path}/TRAIN.csv')
trainDf.drop_duplicates(inplace=True)
trainDf.duplicated().sum()

np.int64(0)

In [ ]:
X = trainDf.drop('Class',axis=1)
y = trainDf['Class']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")

Train: 34430 | Test: 8608

In [ ]:
neg, pos = np.bincount(y_train)
print("neg : ",neg)
print("pos : " ,pos)

neg :  20581
pos :  13849

In [ ]:
scale_pos_weight = neg / pos
print(f"scale_pos_weight: {scale_pos_weight:.4f}")

scale_pos_weight: 1.4861

### print all metrices

In [ ]:
def print_metrics(y_true, y_pred, y_proba, label="Model"):
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    print(f"\n{'='*60}\n  {label}\n{'='*60}")
    for k, v in {
        "Accuracy"                   : accuracy_score(y_true, y_pred),
        "Precision"                  : precision_score(y_true, y_pred),
        "Recall (Sensitivity)"       : recall_score(y_true, y_pred),
        "Specificity (TNR)"          : tn / (tn + fp),
        "F1 Score"                   : f1_score(y_true, y_pred),
        "ROC-AUC"                    : roc_auc_score(y_true, y_proba),
        "Average Precision (PR-AUC)" : average_precision_score(y_true, y_proba),
        "MCC"                        : matthews_corrcoef(y_true, y_pred),
        "Log Loss"                   : log_loss(y_true, y_proba),
    }.items():
        print(f"  {k:<35}: {v:.4f}")
    print(f"\n  TP:{tp}  FP:{fp}  TN:{tn}  FN:{fn}")
    print(classification_report(y_true, y_pred,
          target_names=["Class 0", "Class 1"], digits=4))

train the model

In [ ]:
xgb_model = xgb.XGBClassifier(
    n_estimators=300,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    device='cuda',
    eval_metric='logloss',
    random_state=42,
    use_label_encoder=False
)

xgb_model.fit(
    X_train,y_train,
    eval_set=[(X_test,y_test)],
    verbose=50
)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [11:02:25] WARNING: /__w/xgboost/xgboost/src/context.cc:53: No visible GPU is found, setting device to CPU.
  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [11:02:25] WARNING: /__w/xgboost/xgboost/src/context.cc:207: Device is changed from GPU to CPU as we couldn't find any available GPU on the system.
  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [11:02:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[0]	validation_0-logloss:0.65653
[50]	validation_0-logloss:0.22843
[100]	validation_0-logloss:0.12788
[150]	validation_0-logloss:0.08991
[200]	validation_0-logloss:0.07019
[250]	validation_0-logloss:0.05853
[299]	validation_0-logloss:0.05094

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device='cuda', early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

## for default

In [ ]:
y_pred       = xgb_model.predict(X_test)
y_pred_proba = xgb_model.predict_proba(X_test)[:, 1]
print_metrics(y_test, y_pred, y_pred_proba, "XGBoost Default (GPU)")

============================================================
  XGBoost Default (GPU)
============================================================
  Accuracy                           : 0.9847
  Precision                          : 0.9860
  Recall (Sensitivity)               : 0.9757
  Specificity (TNR)                  : 0.9907
  F1 Score                           : 0.9808
  ROC-AUC                            : 0.9987
  Average Precision (PR-AUC)         : 0.9983
  MCC                                : 0.9681
  Log Loss                           : 0.0509

  TP:3378  FP:48  TN:5098  FN:84
              precision    recall  f1-score   support

     Class 0     0.9838    0.9907    0.9872      5146
     Class 1     0.9860    0.9757    0.9808      3462

    accuracy                         0.9847      8608
   macro avg     0.9849    0.9832    0.9840      8608
weighted avg     0.9847    0.9847    0.9847      8608

### param search - finding best parameters
# false negative - 67 (best till now)

In [ ]:
configs = [
    {'n_estimators': 300, 'max_depth': 6,  'learning_rate': 0.1,  'subsample': 0.8},
    {'n_estimators': 500, 'max_depth': 6,  'learning_rate': 0.05, 'subsample': 0.8},
    {'n_estimators': 300, 'max_depth': 8,  'learning_rate': 0.1,  'subsample': 0.8},
    {'n_estimators': 500, 'max_depth': 8,  'learning_rate': 0.05, 'subsample': 0.9},
    {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.1,  'subsample': 0.8},
]

best_f1, best_model, best_cfg = 0, None, None

for cfg in configs:
  model = xgb.XGBClassifier(
      n_estimators=cfg['n_estimators'],
      max_depth        = cfg['max_depth'],
        learning_rate    = cfg['learning_rate'],
        subsample        = cfg['subsample'],
        colsample_bytree = 0.8,
        scale_pos_weight = scale_pos_weight,
        device           = 'cuda',
        eval_metric      = 'logloss',
        random_state     = 42,
        use_label_encoder= False,
        verbosity        = 0
  )

  model.fit(X_train,y_train)
  preds = model.predict(X_test)
  f1 = f1_score(y_test,preds)
  print(f"  {cfg}  =>  F1: {f1:.4f}")

  if f1 > best_f1:
        best_f1, best_model, best_cfg = f1, model, cfg

print(f"\nBest config : {best_cfg}")
print(f"Best F1     : {best_f1:.4f}")

y_pred_tuned       = best_model.predict(X_test)
y_pred_proba_tuned = best_model.predict_proba(X_test)[:, 1]
print_metrics(y_test, y_pred_tuned, y_pred_proba_tuned, "XGBoost Tuned (GPU)")

  {'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.1, 'subsample': 0.8}  =>  F1: 0.9808
  {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.05, 'subsample': 0.8}  =>  F1: 0.9803
  {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.1, 'subsample': 0.8}  =>  F1: 0.9833
  {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.05, 'subsample': 0.9}  =>  F1: 0.9855
  {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.1, 'subsample': 0.8}  =>  F1: 0.9849

Best config : {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.05, 'subsample': 0.9}
Best F1     : 0.9855

============================================================
  XGBoost Tuned (GPU)
============================================================
  Accuracy                           : 0.9884
  Precision                          : 0.9904
  Recall (Sensitivity)               : 0.9806
  Specificity (TNR)                  : 0.9936
  F1 Score                           : 0.9855
  ROC-AUC                            : 0.9992
  Average Precision (PR-AUC)         : 0.9989
  MCC                                : 0.9758
  Log Loss                           : 0.0372

  TP:3395  FP:33  TN:5113  FN:67
              precision    recall  f1-score   support

     Class 0     0.9871    0.9936    0.9903      5146
     Class 1     0.9904    0.9806    0.9855      3462

    accuracy                         0.9884      8608
   macro avg     0.9887    0.9871    0.9879      8608
weighted avg     0.9884    0.9884    0.9884      8608

## LightGBM - light gradient boosting maching (a tree based algo usage leaf wise tree growth)  False negative :85 best till now

In [ ]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score
)

trainDf = pd.read_csv(f'{file_path}/TRAIN.csv')
trainDf.drop_duplicates(inplace=True)
print(trainDf.duplicated().sum())

X = trainDf.drop('Class',axis=1)
y = trainDf['Class']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")

neg, pos = np.bincount(y_train)
print("neg : ",neg)
print("pos : " ,pos)

scale_pos_weight = neg / pos
print(f"scale_pos_weight: {scale_pos_weight:.4f}")

0
Train: 34430 | Test: 8608
neg :  20581
pos :  13849
scale_pos_weight: 1.4861

In [ ]:
def print_metrics(y_true, y_pred, y_proba, label="Model"):
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    print(f"\n{'='*60}\n  {label}\n{'='*60}")
    for k, v in {
        "Accuracy"                   : accuracy_score(y_true, y_pred),
        "Precision"                  : precision_score(y_true, y_pred),
        "Recall (Sensitivity)"       : recall_score(y_true, y_pred),
        "Specificity (TNR)"          : tn / (tn + fp),
        "F1 Score"                   : f1_score(y_true, y_pred),
        "ROC-AUC"                    : roc_auc_score(y_true, y_proba),
        "Average Precision (PR-AUC)" : average_precision_score(y_true, y_proba),
        "MCC"                        : matthews_corrcoef(y_true, y_pred),
        "Log Loss"                   : log_loss(y_true, y_proba),
    }.items():
        print(f"  {k:<35}: {v:.4f}")
    print(f"\n  TP:{tp}  FP:{fp}  TN:{tn}  FN:{fn}")
    print(classification_report(y_true, y_pred,
          target_names=["Class 0", "Class 1"], digits=4))

In [ ]:
lgb_model = lgb.LGBMClassifier(
     n_estimators = 300,
    learning_rate = 0.1,
    max_depth = -1,          # -1 = no limit
    num_leaves = 31,
    subsample  = 0.8,
    colsample_bytree = 0.8,
    scale_pos_weight = scale_pos_weight,
    random_state = 42,
    verbose = -1,
    n_jobs= -1
)

lgb_model.fit(
    X_train, y_train,
    eval_set   = [(X_test, y_test)],
    callbacks  = [lgb.log_evaluation(50)]  # print every 50 rounds
)

[50]	valid_0's binary_logloss: 0.193214
[100]	valid_0's binary_logloss: 0.121155
[150]	valid_0's binary_logloss: 0.0880505
[200]	valid_0's binary_logloss: 0.0693324
[250]	valid_0's binary_logloss: 0.0577452
[300]	valid_0's binary_logloss: 0.0511551

LGBMClassifier(colsample_bytree=0.8, n_estimators=300, n_jobs=-1,
               random_state=42, scale_pos_weight=np.float64(1.4861000794281176),
               subsample=0.8, verbose=-1)

In [ ]:
y_pred       = lgb_model.predict(X_test)
y_pred_proba = lgb_model.predict_proba(X_test)[:, 1]
print_metrics(y_test, y_pred, y_pred_proba, "LightGBM Default ")

============================================================
  LightGBM Default
============================================================
  Accuracy                           : 0.9845
  Precision                          : 0.9860
  Recall (Sensitivity)               : 0.9754
  Specificity (TNR)                  : 0.9907
  F1 Score                           : 0.9807
  ROC-AUC                            : 0.9986
  Average Precision (PR-AUC)         : 0.9981
  MCC                                : 0.9679
  Log Loss                           : 0.0512

  TP:3377  FP:48  TN:5098  FN:85
              precision    recall  f1-score   support

     Class 0     0.9836    0.9907    0.9871      5146
     Class 1     0.9860    0.9754    0.9807      3462

    accuracy                         0.9845      8608
   macro avg     0.9848    0.9831    0.9839      8608
weighted avg     0.9846    0.9845    0.9845      8608

### param search  False Negative:64 (parameter search on lgbm best till now)

In [ ]:
configs = [
    {'n_estimators': 300, 'num_leaves': 31,  'max_depth': -1, 'learning_rate': 0.1 },
    {'n_estimators': 500, 'num_leaves': 63,  'max_depth': -1, 'learning_rate': 0.05},
    {'n_estimators': 300, 'num_leaves': 127, 'max_depth': -1, 'learning_rate': 0.1 },
    {'n_estimators': 500, 'num_leaves': 63,  'max_depth': 10, 'learning_rate': 0.05},
    {'n_estimators': 500, 'num_leaves': 127, 'max_depth': 15, 'learning_rate': 0.05},
]

best_f1, best_model, best_cfg = 0, None, None

for cfg in configs:
    model = lgb.LGBMClassifier(
        n_estimators     = cfg['n_estimators'],
        num_leaves       = cfg['num_leaves'],
        max_depth        = cfg['max_depth'],
        learning_rate    = cfg['learning_rate'],
        subsample        = 0.8,
        colsample_bytree = 0.8,
        scale_pos_weight = scale_pos_weight,
        device           = 'cpu',
        n_jobs=-1,
        random_state     = 42,
        verbose          = -1
    )
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    f1    = f1_score(y_test, preds)
    print(f"  {cfg}  =>  F1: {f1:.4f}")

    if f1 > best_f1:
        best_f1, best_model, best_cfg = f1, model, cfg

print(f"\nBest config : {best_cfg}")
print(f"Best F1     : {best_f1:.4f}")

  {'n_estimators': 300, 'num_leaves': 31, 'max_depth': -1, 'learning_rate': 0.1}  =>  F1: 0.9807
  {'n_estimators': 500, 'num_leaves': 63, 'max_depth': -1, 'learning_rate': 0.05}  =>  F1: 0.9848
  {'n_estimators': 300, 'num_leaves': 127, 'max_depth': -1, 'learning_rate': 0.1}  =>  F1: 0.9874
  {'n_estimators': 500, 'num_leaves': 63, 'max_depth': 10, 'learning_rate': 0.05}  =>  F1: 0.9842
  {'n_estimators': 500, 'num_leaves': 127, 'max_depth': 15, 'learning_rate': 0.05}  =>  F1: 0.9863

Best config : {'n_estimators': 300, 'num_leaves': 127, 'max_depth': -1, 'learning_rate': 0.1}
Best F1     : 0.9874

In [ ]:
y_pred_tuned       = best_model.predict(X_test)
y_pred_proba_tuned = best_model.predict_proba(X_test)[:, 1]
print_metrics(y_test, y_pred_tuned, y_pred_proba_tuned, "LightGBM Tuned")

============================================================
  LightGBM Tuned
============================================================
  Accuracy                           : 0.9899
  Precision                          : 0.9933
  Recall (Sensitivity)               : 0.9815
  Specificity (TNR)                  : 0.9955
  F1 Score                           : 0.9874
  ROC-AUC                            : 0.9994
  Average Precision (PR-AUC)         : 0.9992
  MCC                                : 0.9790
  Log Loss                           : 0.0354

  TP:3398  FP:23  TN:5123  FN:64
              precision    recall  f1-score   support

     Class 0     0.9877    0.9955    0.9916      5146
     Class 1     0.9933    0.9815    0.9874      3462

    accuracy                         0.9899      8608
   macro avg     0.9905    0.9885    0.9895      8608
weighted avg     0.9899    0.9899    0.9899      8608

### CatBoost False Negative:110

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 10.2 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [ ]:
import numpy as np
import pandas as pd
from catboost import CatBoostClassifier,Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score
)

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/ml-alrIEEEna-gehu'

trainDf = pd.read_csv(f'{file_path}/TRAIN.csv')

trainDf.duplicated().sum()
trainDf.drop_duplicates(inplace=True)
trainDf.duplicated().sum()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

np.int64(0)

In [ ]:
X = trainDf.drop('Class',axis=1)
y = trainDf['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

neg, pos = np.bincount(y_train)
class_weights = [1, neg/pos]
print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")
print(f"Class weights: {class_weights}")

Train: 34430 | Test: 8608
Class weights: [1, np.float64(1.4861000794281176)]

###### catboost pool -> optimize data format

In [ ]:
feature_names = X.columns.tolist()
train_pool = Pool(X_train, y_train, feature_names=feature_names)
test_pool  = Pool(X_test,  y_test,  feature_names=feature_names)

In [ ]:
def print_metrics(y_true, y_pred, y_proba, label="Model"):
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()
    print(f"\n{'='*60}\n  {label}\n{'='*60}")
    for k, v in {
        "Accuracy"                   : accuracy_score(y_true, y_pred),
        "Precision"                  : precision_score(y_true, y_pred),
        "Recall (Sensitivity)"       : recall_score(y_true, y_pred),
        "Specificity (TNR)"          : tn / (tn + fp),
        "F1 Score"                   : f1_score(y_true, y_pred),
        "ROC-AUC"                    : roc_auc_score(y_true, y_proba),
        "Average Precision (PR-AUC)" : average_precision_score(y_true, y_proba),
        "MCC"                        : matthews_corrcoef(y_true, y_pred),
        "Log Loss"                   : log_loss(y_true, y_proba),
    }.items():
        print(f"  {k:<35}: {v:.4f}")
    print(f"\n  TP:{tp}  FP:{fp}  TN:{tn}  FN:{fn}")
    print(classification_report(y_true, y_pred,
          target_names=["Class 0", "Class 1"], digits=4))

In [ ]:
cat_model = CatBoostClassifier(
    iterations       = 300,
    learning_rate    = 0.1,
    depth            = 6,
    class_weights    = class_weights,
    task_type        = 'GPU',
    random_seed      = 42,
    verbose          = 50
)

cat_model.fit(train_pool,eval_set=test_pool)

0:	learn: 0.6297079	test: 0.6299490	best: 0.6299490 (0)	total: 47.5ms	remaining: 14.2s
50:	learn: 0.2638415	test: 0.2750301	best: 0.2750301 (50)	total: 2.78s	remaining: 13.6s
100:	learn: 0.1764170	test: 0.1915631	best: 0.1915631 (100)	total: 4.38s	remaining: 8.63s
150:	learn: 0.1333757	test: 0.1508787	best: 0.1508787 (150)	total: 4.66s	remaining: 4.6s
200:	learn: 0.1060719	test: 0.1257880	best: 0.1257880 (200)	total: 4.92s	remaining: 2.42s
250:	learn: 0.0875146	test: 0.1094334	best: 0.1094334 (250)	total: 5.13s	remaining: 1s
299:	learn: 0.0745402	test: 0.0978040	best: 0.0978040 (299)	total: 5.35s	remaining: 0us
bestTest = 0.09780399813
bestIteration = 299

CatBoostClassifier(class_weights=[1, np.float64(1.4861000794281176)], depth=6, iterations=300, learning_rate=0.1, random_seed=42, task_type='GPU', verbose=50)

In [ ]:
y_pred       = cat_model.predict(test_pool)
y_pred_proba = cat_model.predict_proba(test_pool)[:, 1]
print_metrics(y_test, y_pred, y_pred_proba, "CatBoost Default (GPU)")

============================================================
  CatBoost Default (GPU)
============================================================
  Accuracy                           : 0.9757
  Precision                          : 0.9713
  Recall (Sensitivity)               : 0.9682
  Specificity (TNR)                  : 0.9808
  F1 Score                           : 0.9698
  ROC-AUC                            : 0.9975
  Average Precision (PR-AUC)         : 0.9966
  MCC                                : 0.9495
  Log Loss                           : 0.0967

  TP:3352  FP:99  TN:5047  FN:110
              precision    recall  f1-score   support

     Class 0     0.9787    0.9808    0.9797      5146
     Class 1     0.9713    0.9682    0.9698      3462

    accuracy                         0.9757      8608
   macro avg     0.9750    0.9745    0.9747      8608
weighted avg     0.9757    0.9757    0.9757      8608

### tuning of catboost False Negative:65
catboost get improved after tuning

In [ ]:
configs = [
    {'iterations': 300, 'depth': 6,  'learning_rate': 0.1 },
    {'iterations': 500, 'depth': 6,  'learning_rate': 0.05},
    {'iterations': 300, 'depth': 8,  'learning_rate': 0.1 },
    {'iterations': 500, 'depth': 8,  'learning_rate': 0.05},
    {'iterations': 500, 'depth': 10, 'learning_rate': 0.05},
]

best_f1, best_model, best_cfg = 0, None, None

for cfg in configs:
    model = CatBoostClassifier(
        iterations    = cfg['iterations'],
        depth         = cfg['depth'],
        learning_rate = cfg['learning_rate'],
        class_weights = class_weights,
        task_type     = 'GPU',
        random_seed   = 42,
        verbose       = 0
    )
    model.fit(train_pool)
    preds = model.predict(test_pool)
    f1    = f1_score(y_test, preds)
    print(f"  {cfg}  =>  F1: {f1:.4f}")

    if f1 > best_f1:
        best_f1, best_model, best_cfg = f1, model, cfg

print(f"\nBest config : {best_cfg}")
print(f"Best F1     : {best_f1:.4f}")

y_pred_tuned       = best_model.predict(test_pool)
y_pred_proba_tuned = best_model.predict_proba(test_pool)[:, 1]
print_metrics(y_test, y_pred_tuned, y_pred_proba_tuned, "CatBoost Tuned (GPU)")

  {'iterations': 300, 'depth': 6, 'learning_rate': 0.1}  =>  F1: 0.9698
  {'iterations': 500, 'depth': 6, 'learning_rate': 0.05}  =>  F1: 0.9701
  {'iterations': 300, 'depth': 8, 'learning_rate': 0.1}  =>  F1: 0.9794
  {'iterations': 500, 'depth': 8, 'learning_rate': 0.05}  =>  F1: 0.9776
  {'iterations': 500, 'depth': 10, 'learning_rate': 0.05}  =>  F1: 0.9828

Best config : {'iterations': 500, 'depth': 10, 'learning_rate': 0.05}
Best F1     : 0.9828

============================================================
  CatBoost Tuned (GPU)
============================================================
  Accuracy                           : 0.9862
  Precision                          : 0.9844
  Recall (Sensitivity)               : 0.9812
  Specificity (TNR)                  : 0.9895
  F1 Score                           : 0.9828
  ROC-AUC                            : 0.9990
  Average Precision (PR-AUC)         : 0.9986
  MCC                                : 0.9712
  Log Loss                           : 0.0565

  TP:3397  FP:54  TN:5092  FN:65
              precision    recall  f1-score   support

     Class 0     0.9874    0.9895    0.9884      5146
     Class 1     0.9844    0.9812    0.9828      3462

    accuracy                         0.9862      8608
   macro avg     0.9859    0.9854    0.9856      8608
weighted avg     0.9862    0.9862    0.9862      8608

# Exploring neural network (didnt performed well because it was tabular data and it required high scaling )

In [ ]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score,confusion_matrix,classification_report,
    matthews_corrcoef,log_loss,average_precision_score
)

print(f"TensorFlow version: {tf.__version__}")
print(f"GPU available: {tf.config.list_physical_devices('GPU')}")

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/ml-alrIEEEna-gehu'

trainDf = pd.read_csv(f'{file_path}/TRAIN.csv')

print("duplicates : ",trainDf.duplicated().sum())
trainDf.drop_duplicates(inplace=True)
print("duplicates : ",trainDf.duplicated().sum())

TensorFlow version: 2.19.0
GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
duplicates :  738
duplicates :  0

In [ ]:
X = trainDf.drop('Class',axis=1)
y = trainDf['Class']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype(np.float32)
X_test = scaler.transform(X_test).astype(np.float32)

print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")

neg,pos = np.bincount(y_train.astype(int))
class_weight = {0:1.0, 1 : neg/pos}
print(f"Class weights: {class_weight}")

Train: 34430 | Test: 8608
Class weights: {0: 1.0, 1: np.float64(1.4861000794281176)}

In [ ]:
def print_metrics(y_true,y_pred,y_proba,label="Model"):
  cm = confusion_matrix(y_true,y_pred)
  tn,fp,fn,tp = cm.ravel()
  print(f"\n{'='*60}\n{label}\n{'='*60}")
  for k,v in {
      "Accuracy" : accuracy_score(y_true,y_pred),
      "Precision" : precision_score(y_true,y_pred),
      "Recall (Sensitivity)" : recall_score(y_true,y_pred),
      "Specificity (TNR)" : tn/(tn+fp),
      "F1 Score" : f1_score(y_true,y_pred),
      "ROC-AUC" : roc_auc_score(y_true,y_proba),
      "Average Precision (PR-AUC)" : average_precision_score(y_true,y_proba),
      "MCC" : matthews_corrcoef(y_true,y_pred),
      "Log Loss" : log_loss(y_true,y_proba)
  }.items():
    print(f"  {k:<35}: {v:.4f}")
  print(f"\n TP : {tp} FP : {fp} TN : {tn} FN : {fn}")
  print(classification_report(y_true,y_pred,
                              target_names=['Class 0','Class 1'],digits=4))

In [ ]:
def build_model(input_dim,hidden_dims,dropout=0.3,lr=1e-3):
  model = keras.Sequential()
  model.add(layers.Input(shape=(input_dim,)))

  for h in hidden_dims:
    model.add(layers.Dense(h))
    model.add(layers.BatchNormalization())
    model.add(layers.Activation('relu'))
    model.add(layers.Dropout(dropout))

  model.add(layers.Dense(1,activation='sigmoid'))

  model.compile(
      optimizer=keras.optimizers.Adam(learning_rate=lr),
      loss='binary_crossentropy',
      metrics=['accuracy',
               keras.metrics.AUC(name='auc'),
               keras.metrics.Precision(name='precision'),
               keras.metrics.Recall(name='recall')
               ]
  )

  return model

def get_callbacks():
  return [
      keras.callbacks.EarlyStopping(
          monitor='val_loss',
          patience=10,
          restore_best_weights=True,
          verbose=1
      ),
      keras.callbacks.ReduceLROnPlateau(
          monitor='val_loss',
          factor=0.5,
          patience=5,
          verbose=1
      )
  ]

### default model

In [ ]:
default_model = build_model(
    input_dim = X_train.shape[1],
    hidden_dims = [128,64],
    dropout = 0.3,
    lr = 1e-3
)

default_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 128)            │         6,144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_2 (Activation)       │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_3 (Activation)       │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15,233 (59.50 KB)

 Trainable params: 14,849 (58.00 KB)

 Non-trainable params: 384 (1.50 KB)

### train default model

In [ ]:
history = default_model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    batch_size=1024,
    class_weight=class_weight,
    callbacks=get_callbacks(),
    verbose=1
)

Epoch 1/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9180 - auc: 0.9737 - loss: 0.2494 - precision: 0.9020 - recall: 0.8943 - val_accuracy: 0.9365 - val_auc: 0.9824 - val_loss: 0.1809 - val_precision: 0.9158 - val_recall: 0.9272 - learning_rate: 5.0000e-04
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9116 - auc: 0.9712 - loss: 0.2608 - precision: 0.8797 - recall: 0.9048 - val_accuracy: 0.9398 - val_auc: 0.9830 - val_loss: 0.1741 - val_precision: 0.9365 - val_recall: 0.9122 - learning_rate: 5.0000e-04
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9146 - auc: 0.9713 - loss: 0.2589 - precision: 0.8953 - recall: 0.8947 - val_accuracy: 0.9405 - val_auc: 0.9835 - val_loss: 0.1749 - val_precision: 0.9290 - val_recall: 0.9226 - learning_rate: 5.0000e-04
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9151 - auc: 0.9719 - loss: 0.2575 - precision: 0.8998 - recall: 0.8906 - val_accuracy: 0.9416 - val_auc: 0.9835 - val_loss: 0.1749 - val_precision: 0.9267 - val_recall: 0.9281 - learning_rate: 5.0000e-04
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9167 - auc: 0.9724 - loss: 0.2531 - precision: 0.8957 - recall: 0.8996 - val_accuracy: 0.9377 - val_auc: 0.9831 - val_loss: 0.1780 - val_precision: 0.9202 - val_recall: 0.9255 - learning_rate: 5.0000e-04
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9147 - auc: 0.9725 - loss: 0.2550 - precision: 0.8900 - recall: 0.8986 - val_accuracy: 0.9401 - val_auc: 0.9833 - val_loss: 0.1778 - val_precision: 0.9209 - val_recall: 0.9310 - learning_rate: 5.0000e-04
Epoch 7/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9164 - auc: 0.9740 - loss: 0.2472 - precision: 0.8929 - recall: 0.9004 - val_accuracy: 0.9406 - val_auc: 0.9840 - val_loss: 0.1724 - val_precision: 0.9283 - val_recall: 0.9237 - learning_rate: 5.0000e-04
Epoch 8/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9121 - auc: 0.9717 - loss: 0.2573 - precision: 0.8921 - recall: 0.8907 - val_accuracy: 0.9383 - val_auc: 0.9835 - val_loss: 0.1755 - val_precision: 0.9193 - val_recall: 0.9281 - learning_rate: 5.0000e-04
Epoch 9/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.9191 - auc: 0.9741 - loss: 0.2451 - precision: 0.8953 - recall: 0.9027 - val_accuracy: 0.9398 - val_auc: 0.9838 - val_loss: 0.1748 - val_precision: 0.9225 - val_recall: 0.9284 - learning_rate: 5.0000e-04
Epoch 10/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9138 - auc: 0.9719 - loss: 0.2566 - precision: 0.8828 - recall: 0.9046 - val_accuracy: 0.9430 - val_auc: 0.9844 - val_loss: 0.1696 - val_precision: 0.9378 - val_recall: 0.9191 - learning_rate: 5.0000e-04
Epoch 11/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9161 - auc: 0.9715 - loss: 0.2592 - precision: 0.8990 - recall: 0.8895 - val_accuracy: 0.9412 - val_auc: 0.9841 - val_loss: 0.1740 - val_precision: 0.9237 - val_recall: 0.9307 - learning_rate: 5.0000e-04
Epoch 12/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.9172 - auc: 0.9721 - loss: 0.2559 - precision: 0.8955 - recall: 0.8978 - val_accuracy: 0.9414 - val_auc: 0.9841 - val_loss: 0.1719 - val_precision: 0.9280 - val_recall: 0.9263 - learning_rate: 5.0000e-04
Epoch 13/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9154 - auc: 0.9728 - loss: 0.2512 - precision: 0.8895 - recall: 0.9028 - val_accuracy: 0.9418 - val_auc: 0.9843 - val_loss: 0.1734 - val_precision: 0.9246 - val_recall: 0.9313 - learning_rate: 5.0000e-04
Epoch 14/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.9194 - auc: 0.9738 - loss: 0.2481 - precision: 0.8992 - recall: 0.8971 - val_accuracy: 0.9427 - val_auc: 0.9842 - val_loss: 0.1705 - val_precision: 0.9380 - val_recall: 0.9183 - learning_rate: 5.0000e-04
Epoch 15/100
26/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9208 - auc: 0.9745 - loss: 0.2461 - precision: 0.9066 - recall: 0.8962
Epoch 15: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9203 - auc: 0.9742 - loss: 0.2467 - precision: 0.9045 - recall: 0.8972 - val_accuracy: 0.9428 - val_auc: 0.9844 - val_loss: 0.1736 - val_precision: 0.9267 - val_recall: 0.9315 - learning_rate: 5.0000e-04
Epoch 16/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9179 - auc: 0.9727 - loss: 0.2519 - precision: 0.8947 - recall: 0.9030 - val_accuracy: 0.9431 - val_auc: 0.9846 - val_loss: 0.1709 - val_precision: 0.9312 - val_recall: 0.9269 - learning_rate: 2.5000e-04
Epoch 17/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9191 - auc: 0.9746 - loss: 0.2456 - precision: 0.9014 - recall: 0.8977 - val_accuracy: 0.9426 - val_auc: 0.9847 - val_loss: 0.1721 - val_precision: 0.9264 - val_recall: 0.9313 - learning_rate: 2.5000e-04
Epoch 18/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9164 - auc: 0.9719 - loss: 0.2556 - precision: 0.8980 - recall: 0.8959 - val_accuracy: 0.9425 - val_auc: 0.9848 - val_loss: 0.1719 - val_precision: 0.9281 - val_recall: 0.9289 - learning_rate: 2.5000e-04
Epoch 19/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9191 - auc: 0.9734 - loss: 0.2492 - precision: 0.9016 - recall: 0.8971 - val_accuracy: 0.9430 - val_auc: 0.9848 - val_loss: 0.1706 - val_precision: 0.9330 - val_recall: 0.9246 - learning_rate: 2.5000e-04
Epoch 20/100
31/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9199 - auc: 0.9741 - loss: 0.2486 - precision: 0.9056 - recall: 0.8976
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9198 - auc: 0.9742 - loss: 0.2481 - precision: 0.9044 - recall: 0.8985 - val_accuracy: 0.9441 - val_auc: 0.9848 - val_loss: 0.1697 - val_precision: 0.9357 - val_recall: 0.9246 - learning_rate: 2.5000e-04
Epoch 20: early stopping
Restoring model weights from the end of the best epoch: 10.

In [ ]:
y_proba = default_model.predict(X_test,verbose=0).flatten()
y_pred = (y_proba >= 0.5).astype(int)
print_metrics(y_test.astype(int),y_pred,y_proba,"MLP Default")

============================================================
MLP Default
============================================================
  Accuracy                           : 0.9430
  Precision                          : 0.9378
  Recall (Sensitivity)               : 0.9191
  Specificity (TNR)                  : 0.9590
  F1 Score                           : 0.9284
  ROC-AUC                            : 0.9845
  Average Precision (PR-AUC)         : 0.9795
  MCC                                : 0.8811
  Log Loss                           : 0.1662

 TP : 3182 FP : 211 TN : 4935 FN : 280
              precision    recall  f1-score   support

     Class 0     0.9463    0.9590    0.9526      5146
     Class 1     0.9378    0.9191    0.9284      3462

    accuracy                         0.9430      8608
   macro avg     0.9421    0.9391    0.9405      8608
weighted avg     0.9429    0.9430    0.9429      8608

### params search

In [ ]:
X_train.shape[1]

47

In [ ]:
configs = [
    {'hidden_dims': [128, 64],       'dropout': 0.3, 'lr': 1e-3},
    {'hidden_dims': [256, 128],      'dropout': 0.3, 'lr': 1e-3},
    {'hidden_dims': [256, 128, 64],  'dropout': 0.3, 'lr': 1e-3},
    {'hidden_dims': [512, 256, 128], 'dropout': 0.4, 'lr': 5e-4},
    {'hidden_dims': [256, 128, 64],  'dropout': 0.2, 'lr': 5e-4},
]

best_f1, best_model, best_cfg = 0, None, None

for cfg in configs:
    model = build_model(
        input_dim = X_train.shape[1],
        hidden_dims=cfg['hidden_dims'],
        dropout=cfg['dropout'],
        lr=cfg['lr']
    )

    model.fit(
        X_train,y_train,
        validation_data=(X_test,y_test),
        epochs=100,
        batch_size=1024,
        class_weight=class_weight,
        callbacks=get_callbacks(),
        verbose=0
    )

    y_proba = model.predict(X_test,verbose=0).flatten()
    y_pred = (y_proba >= 0.5).astype(int)
    f1    = f1_score(y_test.astype(int), y_pred)

    print(f"F1 : {f1:.4f}")

    if(f1 > best_f1):
      best_f1, best_model, best_cfg = f1, model,cfg

print(f"\nBest config : {best_cfg}")
print(f"Best F1     : {best_f1:.4f}")

Restoring model weights from the end of the best epoch: 99.
F1 : 0.9258

Epoch 70: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 81: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 93: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.

Epoch 98: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
Epoch 98: early stopping
Restoring model weights from the end of the best epoch: 88.
F1 : 0.9445

Epoch 80: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
Restoring model weights from the end of the best epoch: 99.
F1 : 0.9536
Restoring model weights from the end of the best epoch: 99.
F1 : 0.9441
Restoring model weights from the end of the best epoch: 99.
F1 : 0.9542

Best config : {'hidden_dims': [256, 128, 64], 'dropout': 0.2, 'lr': 0.0005}
Best F1     : 0.9542

In [ ]:
y_proba_tuned = best_model.predict(X_test, verbose=0).flatten()
y_pred_tuned  = (y_proba_tuned >= 0.5).astype(int)
print_metrics(y_test.astype(int), y_pred_tuned, y_proba_tuned, "MLP Tuned")

============================================================
MLP Tuned
============================================================
  Accuracy                           : 0.9633
  Precision                          : 0.9575
  Recall (Sensitivity)               : 0.9509
  Specificity (TNR)                  : 0.9716
  F1 Score                           : 0.9542
  ROC-AUC                            : 0.9926
  Average Precision (PR-AUC)         : 0.9905
  MCC                                : 0.9236
  Log Loss                           : 0.1054

 TP : 3292 FP : 146 TN : 5000 FN : 170
              precision    recall  f1-score   support

     Class 0     0.9671    0.9716    0.9694      5146
     Class 1     0.9575    0.9509    0.9542      3462

    accuracy                         0.9633      8608
   macro avg     0.9623    0.9613    0.9618      8608
weighted avg     0.9633    0.9633    0.9633      8608

# Stacking best models
### xgboost ,lightgbm, ExtraTreesClassifier
# all above algos gave best results and they are getting used without tuning model still gives FALSE NEGATIVE 49 which is best among all models

In [ ]:
import numpy as np
import pandas as pd

import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import ExtraTreesClassifier,StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score
)

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/ml-alrIEEEna-gehu'

trainDf = pd.read_csv(file_path+'/TRAIN.csv')
print(trainDf.duplicated().sum())
trainDf.drop_duplicates(inplace=True)
print(trainDf.duplicated().sum())

Mounted at /content/drive
738
0

In [ ]:
X = trainDf.drop('Class',axis=1)
y = trainDf['Class']

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,
                                                 test_size=0.2,stratify=y)

neg,pos = np.bincount(y_train)
scale_pos_weight =  neg if pos == 0 else neg/pos
print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")
print(f"Class weights: {scale_pos_weight}")

Train: 34430 | Test: 8608
Class weights: 1.4861000794281176

In [ ]:
def print_metrics(y_true,y_pred,y_proba,label="Model"):
  cm = confusion_matrix(y_true,y_pred)
  tn,fp,fn,tp = cm.ravel()
  print(f"\n{"-"*50}\n {label}\n {'-'*80}")
  for k,v in {
      "Accuracy" : accuracy_score(y_true,y_pred),
      "Precision" : precision_score(y_true,y_pred),
      "Recall (Sensitivity)" : recall_score(y_true,y_pred),
      "Specificity (TNR)" : tn/(tn+fp),
      "F1 Score" : f1_score(y_true,y_pred),
      "ROC-AUC" : roc_auc_score(y_true,y_proba),
      "Average Precision (PR-AUC)" : average_precision_score(y_true,y_proba),
      "MCC" : matthews_corrcoef(y_true,y_pred),
      "Log Loss" : log_loss(y_true,y_proba)
  }.items():
    print(f"{k:<35} : {v:.4f}")

  print(f"\n TP : {tp} FP : {fp} TN : {tn} FN : {fn}")
  print(classification_report(y_true,y_pred,
        target_names=['Class 0','Class 1'],digits=4))

In [ ]:
lgb_model = lgb.LGBMClassifier(
    n_estimators=500,
    num_leaves=63,
    max_depth=-1,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    device='cpu',
    n_jobs=-1,
    random_state=42,
    verbose=-1
)

xgb_model = xgb.XGBClassifier(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    device='cuda',
    eval_metrics='logloss',
    random_state=42,
    verbosity=0
)

et_model = ExtraTreesClassifier(
    n_estimators=200,
    max_features='sqrt',
    class_weight='balanced',
    bootstrap=False,
    random_state=42,
    n_jobs=-1
)

### stack model

In [ ]:
stack_model = StackingClassifier(
    estimators=[
        ('lgb', lgb_model),
        ('xgb', xgb_model),
        ('et', et_model)
    ],
    final_estimator = LogisticRegression(
        C = 1.0,
        class_weight = 'balanced',
        max_iter=5000,
        solver='lbfgs',
        random_state = 42
    ),
    cv = 5,
    stack_method='predict_proba',
    passthrough=True,
    n_jobs=-1,
    verbose=1
)

print("Training stack model...\n and each base model trains 5 times for CV")
stack_model.fit(X_train,y_train)

Training stack model...
 and each base model trains 5 times for CV

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

StackingClassifier(cv=5,
                   estimators=[('lgb',
                                LGBMClassifier(colsample_bytree=0.8,
                                               device='cpu', learning_rate=0.05,
                                               n_estimators=500, n_jobs=-1,
                                               num_leaves=63, random_state=42,
                                               scale_pos_weight=np.float64(1.4861000794281176),
                                               subsample=0.8, verbose=-1)),
                               ('xgb',
                                XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=No...
                                              min_child_weight=None,
                                              missing=nan,
                                              monotone_constraints=None,
                                              multi_strategy=None,
                                              n_estimators=500, n_jobs=None, ...)),
                               ('et',
                                ExtraTreesClassifier(class_weight='balanced',
                                                     n_estimators=200,
                                                     n_jobs=-1,
                                                     random_state=42))],
                   final_estimator=LogisticRegression(class_weight='balanced',
                                                      max_iter=5000,
                                                      random_state=42),
                   n_jobs=-1, passthrough=True, stack_method='predict_proba',
                   verbose=1)

In [ ]:
y_pred       = stack_model.predict(X_test)
y_pred_proba = stack_model.predict_proba(X_test)[:, 1]
print_metrics(y_test, y_pred, y_pred_proba, "Stacking Ensemble (LGB + XGB + ET)")

--------------------------------------------------
 Stacking Ensemble (LGB + XGB + ET)
 --------------------------------------------------------------------------------
Accuracy                            : 0.9900
Precision                           : 0.9893
Recall (Sensitivity)                : 0.9858
Specificity (TNR)                   : 0.9928
F1 Score                            : 0.9876
ROC-AUC                             : 0.9996
Average Precision (PR-AUC)          : 0.9994
MCC                                 : 0.9792
Log Loss                            : 0.0276

 TP : 3413 FP : 37 TN : 5109 FN : 49
              precision    recall  f1-score   support

     Class 0     0.9905    0.9928    0.9917      5146
     Class 1     0.9893    0.9858    0.9876      3462

    accuracy                         0.9900      8608
   macro avg     0.9899    0.9893    0.9896      8608
weighted avg     0.9900    0.9900    0.9900      8608

# store the model and save predicted output

In [ ]:
import numpy as np
import pandas as pd
import pickle

drive.mount('/content/drive')

save_dir = '/content/drive/MyDrive/ml-alrIEEEna-gehu'

with open (save_dir + '/stacking_model.pkl', 'wb') as f:
  pickle.dump(stack_model, f)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
testDf = pd.read_csv(save_dir + '/TEST.csv')
print(testDf.head())

   ID       F01       F02       F03  ...       F44       F45       F46       F47
0   1  0.277497  0.011515  0.009359  ... -0.001117  0.043216 -0.000077 -0.040124
1   2  0.158754  0.013861  0.020935  ...  0.044507  0.007523 -0.000283 -0.007837
2   3  0.504418  0.009106  0.007395  ... -0.011417 -0.004844 -0.034235 -0.001832
3   4  0.556345  0.005370  0.005670  ... -0.051971 -0.085069 -0.000110  0.045889
4   5  0.128356  0.010014  0.016144  ... -0.000206 -0.011331  0.000441 -0.025263

[5 rows x 48 columns]

In [ ]:
ids = testDf['ID']
X_test = testDf.drop('ID',axis=1)

prediction = stack_model.predict(X_test)

final = pd.DataFrame(
    {
        "ID" : ids,
        "Class" : prediction
    }
)

final.head()

   ID  Class
0   1      1
1   2      0
2   3      1
3   4      0
4   5      0

In [ ]:
final.to_csv(save_dir+'/FINAL.csv',index=False)

# Threshold Tuning
# try to predict using other threshold rather than default
- slight improvement in precision of class 0 but it slightly  increased the false negative (so we don't consider it because we required to keep false negative as minimum as possible)
- although it reduces the false positive by 8 but it increased the false negative by 4 , so at the end we need false negative as minimum as possible

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
file_path = '/content/drive/MyDrive/ml-alrIEEEna-gehu/'
!ls {file_path}

FINAL.csv      stacking_model.pkl	       TEST.csv
new_FINAL.csv  stacking_model_with_4_base.pkl  TRAIN.csv

In [ ]:
import pickle
model_path = file_path + 'stacking_model.pkl'
with open (model_path,'rb') as f:
  stack_model = pickle.load(f)

print("model type ",type(stack_model))

model type  <class 'sklearn.ensemble._stacking.StackingClassifier'>

In [ ]:
from sklearn.metrics import f1_score,confusion_matrix
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd

trainDf = pd.read_csv(file_path + 'TRAIN.csv')
print(trainDf.duplicated().sum())

trainDf.drop_duplicates(inplace=True)

print(trainDf.duplicated().sum())

738
0

In [ ]:
X = trainDf.drop('Class',axis=1)
y = trainDf['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

y_pred_proba = stack_model.predict_proba(X_test)[:, 1]

best_thresh, best_f1 = 0.5, 0

for thresh in np.arange(0.1,0.9,0.01):
  y_pred_t = (y_pred_proba >= thresh).astype(int)
  f1 = f1_score(y_test,y_pred_t)

  if f1 > best_f1:
    best_f1 = f1
    best_thresh = thresh

print(f"Default Threshold F1 : {f1_score(y_test,(y_pred_proba >= 0.5).astype(int)):.4f}")
print(f"Best Threshold : {best_thresh:.2f}")
print(f"Best F1 : {best_f1:.4f}")

# Final prediction with best threshold
y_pred_best = (y_pred_proba >= best_thresh).astype(int)
cm = confusion_matrix(y_test,y_pred_best)
tn,fp,fn,tp = cm.ravel()

print(f'\n{'-'*30}  Confusion metrices  {'-'*30}\n')
print(f' TP : {tp} FP : {fp} TN : {tn} FN : {fn}')

Default Threshold F1 : 0.9876
Best Threshold : 0.56
Best F1 : 0.9881

------------------------------  Confusion metrices  ------------------------------

 TP : 3409 FP : 29 TN : 5117 FN : 53

### trying threshold prediction

In [ ]:
save_dir = '/content/drive/MyDrive/ml-alrIEEEna-gehu'

testDf = pd.read_csv(file_path + 'TEST.csv')
print(testDf.head())

ids = testDf['ID']
X_test = testDf.drop('ID',axis=1)

# Predict with best threshold

predictions = (stack_model.predict_proba(X_test)[:, 1] >= best_thresh).astype(int)

final = pd.DataFrame(
    {
        "ID" : ids,
        "CLASS" : prediction
    }
)

print(final.head())

final.to_csv(save_dir+'/threshold_FINAL.csv',index=False)

   ID       F01       F02       F03       F04       F05       F06       F07  \
0   1  0.277497  0.011515  0.009359  0.011706  0.015613  0.063679  0.021114
1   2  0.158754  0.013861  0.020935  0.002451  0.005939  0.006830  0.006934
2   3  0.504418  0.009106  0.007395  0.009073  0.029486  0.086782  0.122499
3   4  0.556345  0.005370  0.005670  0.005167  0.013731  0.014570  0.014776
4   5  0.128356  0.010014  0.016144  0.003891  0.004472  0.005297  0.007538

        F08       F09  ...       F38       F39        F40       F41       F42  \
0  0.152000  0.220904  ...  2.974426  0.009399   0.015668  0.001999 -0.000937
1  0.117209  0.103432  ...  2.619811  0.029324  -0.003211  0.037691 -0.083697
2  0.179376  0.445695  ...  4.411972 -0.171520  -0.866895 -0.070657  0.034070
3  0.522296  0.189882  ...  2.709162  0.044236  19.880789 -2.144453 -1.792552
4  0.075874  0.101176  ...  2.872020 -0.056908   0.006535  0.070059 -0.007989

        F43       F44       F45       F46       F47
0  0.010605 -0.001117  0.043216 -0.000077 -0.040124
1  0.006595  0.044507  0.007523 -0.000283 -0.007837
2 -0.000493 -0.011417 -0.004844 -0.034235 -0.001832
3 -0.034137 -0.051971 -0.085069 -0.000110  0.045889
4  0.004089 -0.000206 -0.011331  0.000441 -0.025263

[5 rows x 48 columns]
   ID  CLASS
0   1      1
1   2      0
2   3      1
3   4      0
4   5      0

In [ ]:
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score
)

def print_metrics(y_true,y_pred,y_proba,label="Model"):
  cm = confusion_matrix(y_true,y_pred)
  tn,fp,fn,tp = cm.ravel()
  print(f"\n{"-"*50}\n {label}\n {'-'*80}")
  for k,v in {
      "Accuracy" : accuracy_score(y_true,y_pred),
      "Precision" : precision_score(y_true,y_pred),
      "Recall (Sensitivity)" : recall_score(y_true,y_pred),
      "Specificity (TNR)" : tn/(tn+fp),
      "F1 Score" : f1_score(y_true,y_pred),
      "ROC-AUC" : roc_auc_score(y_true,y_proba),
      "Average Precision (PR-AUC)" : average_precision_score(y_true,y_proba),
      "MCC" : matthews_corrcoef(y_true,y_pred),
      "Log Loss" : log_loss(y_true,y_proba)
  }.items():
    print(f"{k:<35} : {v:.4f}")

  print(f"\n TP : {tp} FP : {fp} TN : {tn} FN : {fn}")
  print(classification_report(y_true,y_pred,
        target_names=['Class 0','Class 1'],digits=4))

In [ ]:
print_metrics(y_test, y_pred_best, y_pred_proba, "Stacking Tuned Threshold")

--------------------------------------------------
 Stacking Tuned Threshold
 --------------------------------------------------------------------------------
Accuracy                            : 0.9905
Precision                           : 0.9916
Recall (Sensitivity)                : 0.9847
Specificity (TNR)                   : 0.9944
F1 Score                            : 0.9881
ROC-AUC                             : 0.9996
Average Precision (PR-AUC)          : 0.9994
MCC                                 : 0.9802
Log Loss                            : 0.0276

 TP : 3409 FP : 29 TN : 5117 FN : 53
              precision    recall  f1-score   support

     Class 0     0.9897    0.9944    0.9921      5146
     Class 1     0.9916    0.9847    0.9881      3462

    accuracy                         0.9905      8608
   macro avg     0.9907    0.9895    0.9901      8608
weighted avg     0.9905    0.9905    0.9905      8608

# adding catboost in stacking model
**now build a stack model with xgboost lgboost extraTree and catboost**

In [ ]:
! pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [ ]:
import numpy as np
import pandas as pd

import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier,StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix, classification_report,
    matthews_corrcoef, log_loss, average_precision_score
)

df = pd.read_csv(file_path + 'TRAIN.csv')
print(df.duplicated().sum())
df.drop_duplicates(inplace=True)
print(df.duplicated().sum())

X = df.drop('Class',axis=1)
y = df['Class']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

neg, pos         = np.bincount(y_train)
scale_pos_weight = float(neg / pos)
class_weights    = [1, neg / pos]

print(f"Train: {X_train.shape[0]} | Test: {X_test.shape[0]}")

738
0
Train: 34430 | Test: 8608

In [ ]:
def print_metrics(y_true,y_pred,y_proba,label="Model"):
  cm = confusion_matrix(y_true,y_pred)
  tn,fp,fn,tp = cm.ravel()
  print(f"\n{"-"*50}\n {label}\n {'-'*80}")
  for k,v in {
      "Accuracy" : accuracy_score(y_true,y_pred),
      "Precision" : precision_score(y_true,y_pred),
      "Recall (Sensitivity)" : recall_score(y_true,y_pred),
      "Specificity (TNR)" : tn/(tn+fp),
      "F1 Score" : f1_score(y_true,y_pred),
      "ROC-AUC" : roc_auc_score(y_true,y_proba),
      "Average Precision (PR-AUC)" : average_precision_score(y_true,y_proba),
      "MCC" : matthews_corrcoef(y_true,y_pred),
      "Log Loss" : log_loss(y_true,y_proba)
  }.items():
    print(f"{k:<35} : {v:.4f}")

  print(f"\n TP : {tp} FP : {fp} TN : {tn} FN : {fn}")
  print(classification_report(y_true,y_pred,
        target_names=['Class 0','Class 1'],digits=4))

In [ ]:
lgb_model = lgb.LGBMClassifier(
    n_estimators=500,
    num_leaves=63,
    max_depth=-1,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    device='cpu',
    n_jobs=-1,
    random_state=42,
    verbose=-1
)

xgb_model = xgb.XGBClassifier(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.9,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    device='cuda',
    eval_metrics='logloss',
    random_state=42,
    verbosity=0
)

et_model = ExtraTreesClassifier(
    n_estimators=200,
    max_features='sqrt',
    class_weight='balanced',
    bootstrap=False,
    random_state=42,
    n_jobs=-1
)

cat_model = CatBoostClassifier(
    iterations=500,
    depth=10,
    learning_rate=0.05,
    scale_pos_weight=scale_pos_weight,
    task_type='CPU',
    thread_count=-1,
    random_state=42,
    verbose=0
)

# stacking with 4 base model

stack_model_with_4_base = StackingClassifier(
    estimators=[
        ('lgb',lgb_model),
        ('xgb',xgb_model),
        ('et',et_model),
        ('cat',cat_model)
    ],
    final_estimator=LogisticRegression(
        C=1.0,
        class_weight='balanced',
        max_iter=5000,
        solver='lbfgs',
        random_state=42
    ),
    cv=5,
    stack_method='predict_proba',
    passthrough=True,
    n_jobs=-1,
    verbose=1
)

print("Training stack model...\n and each base model trains 5 times for CV")

stack_model_with_4_base.fit(X_train,y_train)

Training stack model...
 and each base model trains 5 times for CV

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

StackingClassifier(cv=5,
                   estimators=[('lgb',
                                LGBMClassifier(colsample_bytree=0.8,
                                               device='cpu', learning_rate=0.05,
                                               n_estimators=500, n_jobs=-1,
                                               num_leaves=63, random_state=42,
                                               scale_pos_weight=1.4861000794281176,
                                               subsample=0.8, verbose=-1)),
                               ('xgb',
                                XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsample...
                                                     n_estimators=200,
                                                     n_jobs=-1,
                                                     random_state=42)),
                               ('cat',
                                CatBoostClassifier(depth=10, iterations=500, learning_rate=0.05, random_state=42, scale_pos_weight=1.4861000794281176, task_type='CPU', verbose=0))],
                   final_estimator=LogisticRegression(class_weight='balanced',
                                                      max_iter=5000,
                                                      random_state=42),
                   n_jobs=-1, passthrough=True, stack_method='predict_proba',
                   verbose=1)

In [ ]:
y_pred = stack_model_with_4_base.predict(X_test)
y_pred_proba = stack_model_with_4_base.predict_proba(X_test)[:, 1]
print_metrics(y_test, y_pred, y_pred_proba,"stacking with (LGB + XGB + ET + Cat)")

--------------------------------------------------
 stacking with (LGB + XGB + ET + Cat)
 --------------------------------------------------------------------------------
Accuracy                            : 0.9898
Precision                           : 0.9890
Recall (Sensitivity)                : 0.9856
Specificity (TNR)                   : 0.9926
F1 Score                            : 0.9873
ROC-AUC                             : 0.9996
Average Precision (PR-AUC)          : 0.9995
MCC                                 : 0.9787
Log Loss                            : 0.0274

 TP : 3412 FP : 38 TN : 5108 FN : 50
              precision    recall  f1-score   support

     Class 0     0.9903    0.9926    0.9915      5146
     Class 1     0.9890    0.9856    0.9873      3462

    accuracy                         0.9898      8608
   macro avg     0.9896    0.9891    0.9894      8608
weighted avg     0.9898    0.9898    0.9898      8608

### compare with previous stacking
**- still not better than 3 base model stacking**

In [ ]:
print(f"  Stacking (3 models) F1  : 0.9876  FN: 49")
print(f"  Stacking (4 models) F1  : {f1_score(y_test, y_pred):.4f}  FN: {confusion_matrix(y_test, y_pred).ravel()[2]}")

  Stacking (3 models) F1  : 0.9876  FN: 49
  Stacking (4 models) F1  : 0.9873  FN: 50

### for 4 base stack model predict

In [ ]:
save_dir = '/content/drive/MyDrive/ml-alrIEEEna-gehu'

with open (save_dir + '/stacking_model_with_4_base.pkl', 'wb') as f:
  pickle.dump(stack_model, f)

testDf = pd.read_csv(file_path + 'TEST.csv')
print(testDf.head())

ids = testDf['ID']
X_test = testDf.drop('ID',axis=1)

prediction = stack_model.predict(X_test)

final = pd.DataFrame(
    {
        "ID" : ids,
        "CLASS" : prediction
    }
)

print(final.head())

final.to_csv(save_dir+'/new_FINAL.csv',index=False)

   ID       F01       F02       F03       F04       F05       F06       F07  \
0   1  0.277497  0.011515  0.009359  0.011706  0.015613  0.063679  0.021114
1   2  0.158754  0.013861  0.020935  0.002451  0.005939  0.006830  0.006934
2   3  0.504418  0.009106  0.007395  0.009073  0.029486  0.086782  0.122499
3   4  0.556345  0.005370  0.005670  0.005167  0.013731  0.014570  0.014776
4   5  0.128356  0.010014  0.016144  0.003891  0.004472  0.005297  0.007538

        F08       F09  ...       F38       F39        F40       F41       F42  \
0  0.152000  0.220904  ...  2.974426  0.009399   0.015668  0.001999 -0.000937
1  0.117209  0.103432  ...  2.619811  0.029324  -0.003211  0.037691 -0.083697
2  0.179376  0.445695  ...  4.411972 -0.171520  -0.866895 -0.070657  0.034070
3  0.522296  0.189882  ...  2.709162  0.044236  19.880789 -2.144453 -1.792552
4  0.075874  0.101176  ...  2.872020 -0.056908   0.006535  0.070059 -0.007989

        F43       F44       F45       F46       F47
0  0.010605 -0.001117  0.043216 -0.000077 -0.040124
1  0.006595  0.044507  0.007523 -0.000283 -0.007837
2 -0.000493 -0.011417 -0.004844 -0.034235 -0.001832
3 -0.034137 -0.051971 -0.085069 -0.000110  0.045889
4  0.004089 -0.000206 -0.011331  0.000441 -0.025263

[5 rows x 48 columns]
   ID  CLASS
0   1      1
1   2      0
2   3      1
3   4      0
4   5      0